sub-RAT123/sub-RAT123.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 64, in main
    metadata = nwb2asset(
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 330, in nwb2asset
    asset = metadata2asset(metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 379, in metadata2asset
    return extract_model(models.BareAssetMeta, metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 234, in extract_model
    value = kwargs.get(field, extract_field(field, metadata))
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 303, in extract_field
    return FIELD_EXTRACTORS[field](metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 283, in extract_digest
    return {models.DigestType[metadata["digest_type"]]: metadata["digest"]}
  File "/home/dandi/miniconda3/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'sha256'

sub-anm372793/sub-anm372793_behavior+ecephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 64, in main
    metadata = nwb2asset(
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 330, in nwb2asset
    asset = metadata2asset(metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 379, in metadata2asset
    return extract_model(models.BareAssetMeta, metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 234, in extract_model
    value = kwargs.get(field, extract_field(field, metadata))
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 303, in extract_field
    return FIELD_EXTRACTORS[field](metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 283, in extract_digest
    return {models.DigestType[metadata["digest_type"]]: metadata["digest"]}
  File "/home/dandi/miniconda3/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'sha256'

sub-anm369962/sub-anm369962_behavior+ecephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 64, in main
    metadata = nwb2asset(
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 330, in nwb2asset
    asset = metadata2asset(metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 379, in metadata2asset
    return extract_model(models.BareAssetMeta, metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 234, in extract_model
    value = kwargs.get(field, extract_field(field, metadata))
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 303, in extract_field
    return FIELD_EXTRACTORS[field](metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 283, in extract_digest
    return {models.DigestType[metadata["digest_type"]]: metadata["digest"]}
  File "/home/dandi/miniconda3/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'sha256'

sub-anm369963/sub-anm369963_behavior+ecephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 64, in main
    metadata = nwb2asset(
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 330, in nwb2asset
    asset = metadata2asset(metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 379, in metadata2asset
    return extract_model(models.BareAssetMeta, metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 234, in extract_model
    value = kwargs.get(field, extract_field(field, metadata))
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 303, in extract_field
    return FIELD_EXTRACTORS[field](metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 283, in extract_digest
    return {models.DigestType[metadata["digest_type"]]: metadata["digest"]}
  File "/home/dandi/miniconda3/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'sha256'

sub-anm369964/sub-anm369964_behavior+ecephys.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 64, in main
    metadata = nwb2asset(
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 330, in nwb2asset
    asset = metadata2asset(metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 379, in metadata2asset
    return extract_model(models.BareAssetMeta, metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 234, in extract_model
    value = kwargs.get(field, extract_field(field, metadata))
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 303, in extract_field
    return FIELD_EXTRACTORS[field](metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 283, in extract_digest
    return {models.DigestType[metadata["digest_type"]]: metadata["digest"]}
  File "/home/dandi/miniconda3/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'sha256'

